### ISSUE TITLE
Freshly installed,  Arch linux.

### ISSUE THREAD

**Issue by fbievan** [paniash/dotfiles#1]
![image](https://user-images.githubusercontent.com/17110707/118719126-afd47280-b7ed-11eb-860b-3c4478ed5129.png)

**Comment by paniash** [comment]
@fbievan Hi! I would suggest removing LICENSE and README, since they aren't configuration files. Haven't used stow personally. Let me know if this helps, otherwise I'll see what I can do from my end.

**Comment by fbievan** [comment]
What i did to simply get this working is just
